+STARTUP: overview
#+TITLE: Emacs config
#+CREATOR: Maksim Yegorov
#+LANGUAGE: en
#+OPTIONS: num:nil

[[https://github.com/myegorov/.emacs.d][Repository]]

* Install

=git clone https://github.com/myegorov/.emacs.d ~/.emacs.d=

* Packages

For all packages, make sure they're installed:
#+BEGIN_SRC emacs-lisp
  (setq use-package-always-ensure t)
#+END_SRC

Source .zshrc or similar:
#+BEGIN_SRC emacs-lisp
  (setq shell-file-name "zsh")
  (setq shell-command-switch "-ic")
  (use-package exec-path-from-shell
    :ensure t
    :config
    (exec-path-from-shell-initialize))
#+END_SRC

Org-mode eye candy:
#+BEGIN_SRC emacs-lisp
  (use-package org-bullets
    :ensure t
    :config 
      (add-hook 'org-mode-hook (lambda () (org-bullets-mode 1))))
#+END_SRC

Autocomplete w/ helpfile:
#+BEGIN_SRC emacs-lisp
  (use-package which-key
    :ensure t
    :config (which-key-mode))
#+END_SRC

Try packages without installing:
#+BEGIN_SRC emacs-lisp
  (use-package try
    :ensure t)
#+END_SRC

Move cursor to any location in buffer:
#+BEGIN_SRC emacs-lisp
  ;; jump to char with M-s
  (use-package avy
    :ensure t
    :bind ("M-s" . avy-goto-char))
#+END_SRC

Balance pairs of parens/braces/brackets etc. when programming:
#+BEGIN_SRC emacs-lisp
  (use-package smartparens-config
      :ensure smartparens
      :bind (:map smartparens-mode-map
             ("C-M-a" . sp-beginning-of-sexp)
             ("C-M-e" . sp-end-of-sexp)
             ("C-x <down>" . sp-down-sexp)
             ("C-x <up>" . sp-up-sexp))
	     ;; wrap with C-M-<SPC>
      :config
      (progn
	(show-smartparens-global-mode t)))

  (add-hook 'prog-mode-hook 'turn-on-smartparens-strict-mode)
  (add-hook 'markdown-mode-hook 'turn-on-smartparens-strict-mode)
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (use-package paredit
    :ensure t
    :config
    (add-hook 'emacs-lisp-mode-hook 'enable-paredit-mode)
    (add-hook 'lisp-mode-hook 'enable-paredit-mode)
    ;; enable in the *scratch* buffer
    (add-hook 'lisp-interaction-mode-hook 'enable-paredit-mode))
#+END_SRC

Jump to definition (guess):
#+BEGIN_SRC emacs-lisp
  ;; install ag (https://github.com/ggreer/the_silver_searcher)
  (use-package dumb-jump
    :ensure t
    :bind (("C-M-g" . dumb-jump-go)
           ("C-M-p" . dumb-jump-back)
           ("C-M-," . dumb-jump-quick-look)))
#+END_SRC

Fuzzy file finder:
#+BEGIN_SRC emacs-lisp
  ;; must install fzf using package manager for the distro (e.g. pacman -S fzf)
  ;; add to .zshrc to enable fzf find hidden files:
  ;;    export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""'
  ;; invoke with M-x fzf
  (use-package fzf
    :ensure t)
#+END_SRC

Easily switch between windows with C-x o:
#+BEGIN_SRC emacs-lisp
  (use-package ace-window
    :ensure t
    :init
    (progn
      (global-set-key [remap other-window] 'ace-window)
      ))
#+END_SRC

Install counsel, ivy and swiper.
Use swiper search instead of interactive search (C-s):
#+BEGIN_SRC emacs-lisp
  (use-package counsel
    :ensure t
    :bind (
	   ("M-x" . counsel-M-x)
	   ("C-x C-f" . counsel-find-file))
    :config
    (progn
      (define-key read-expression-map (kbd "C-r") 'counsel-expression-history)
  
      ))

  (use-package ivy
    :ensure t
    :diminish (ivy-mode)
    :bind (("C-x b" . ivy-switch-buffer)
	   ("C-c C-r" . ivy-resume))
    :config
    (ivy-mode 1)
    (setq ivy-use-virtual-buffers t)
    (setq ivy-count-format "%d/%d")
    (setq ivy-display-style 'fancy))


  (use-package swiper
    :ensure t
    :bind (("C-s" . swiper)
	   ("C-r" . swiper)
      ))
#+END_SRC

Auto-complete with company-mode in all buffers:
#+BEGIN_SRC emacs-lisp
  ;; Completion will start automatically after you type a few letters.
  ;; Use M-n and M-p to select, <return> to complete or <tab> to
  ;; complete the common part. Search through the completions with C-s,
  ;; C-r and C-o. Press M-(digit) to quickly complete with one of the
  ;; first 10 candidates. Type M-x company-complete to initiate
  ;; completion manually (or trigger via <C-Tab>). 

  ;; When the completion candidates are shown, press <f1> to display the
  ;; documentation for the selected candidate, or C-w to see its source.
  ;; Not all back-ends support this.
  (use-package company
    :ensure t
    :diminish
    :config
    (add-hook 'after-init-hook 'global-company-mode)

    ;; don't display candidates unless explicitly asked for
    (setq company-idle-delay nil)
    (global-set-key (kbd "C-TAB") 'company-complete-commobn)

    (use-package company-anaconda
      :ensure t
      :config
      (add-to-list 'company-backends 'company-anaconda)))
#+END_SRC

Tree directory browser (turn on/off with "C-x C-n")
#+BEGIN_SRC emacs-lisp
  (use-package dired-sidebar
    :ensure t
    :bind (("C-x C-n" . dired-sidebar-toggle-sidebar))
    :commands (dired-sidebar-toggle-sidebar))
#+END_SRC

Flycheck lints multiple languages (must install plugins for each!)
#+BEGIN_SRC emacs-lisp
  (use-package flycheck
    :ensure t
    :init (global-flycheck-mode))
#+END_SRC

Send buffer to interpreter with =isend-mode=.
Open ansi-term (S-<Enter>) and start interpreter in the buffer.
Make sure the term buffer is not read-only (C-c j C-x C-q).
M-x isend-associate RET *ansi-term* RET
C-<RET> will send a line (or active region) to ansi-term.
#+BEGIN_SRC emacs-lisp
  (use-package isend-mode
    :ensure t)
#+END_SRC

Send line/region to REPL for multiple languages with C-<RET>:
#+BEGIN_SRC emacs-lisp
  ;; to add languages other than CLISP, Scheme, Python, Scala: https://github.com/kaz-yos/eval-in-repl
  (use-package eval-in-repl
    :ensure t
    :config
    (setq eir-jump-after-eval nil)
    (setq eir-always-split-script-window t)
    (setq eir-delete-other-windows t)
    (setq eir-repl-placement 'right)
    ;; ielm support (for emacs lisp)
    (require 'eval-in-repl-ielm)
    ;; for .el files
    (define-key emacs-lisp-mode-map (kbd "<C-return>") 'eir-eval-in-ielm)
    ;; for *scratch*
    (define-key lisp-interaction-mode-map (kbd "<C-return>") 'eir-eval-in-ielm)
    ;; for M-x info
    (eval-after-load "info"
      '(define-key Info-mode-map (kbd "<C-return>") 'eir-eval-in-ielm))

    ;;; SLIME support (for Common Lisp)
    (require 'slime) ; if not done elsewhere
    (require 'eval-in-repl-slime)
    (add-hook 'lisp-mode-hook
		      '(lambda ()
			 (local-set-key (kbd "<C-return>") 'eir-eval-in-slime)))

    ;;; Scheme support
    (require 'eval-in-repl-geiser)
    (add-hook 'geiser-mode-hook
		      '(lambda ()
			 (local-set-key (kbd "<C-return>") 'eir-eval-in-geiser)))

    ;;; Python support
    ;; (require 'python) ; if not done elsewhere
    (require 'eval-in-repl-python)
    (add-hook 'python-mode-hook
	      '(lambda ()
		 (local-set-key (kbd "<C-return>") 'eir-eval-in-python)))

    ;; Shell support
    (require 'eval-in-repl-shell)
    (add-hook 'sh-mode-hook
	      '(lambda()
		 (local-set-key (kbd "C-<return>") 'eir-eval-in-shell)))
    ;; Version with opposite behavior to eir-jump-after-eval configuration
    (defun eir-eval-in-shell2 ()
      "eval-in-repl for shell script (opposite behavior)

    This version has the opposite behavior to the eir-jump-after-eval
    configuration when invoked to evaluate a line."
      (interactive)
      (let ((eir-jump-after-eval (not eir-jump-after-eval)))
	   (eir-eval-in-shell)))
      (add-hook 'sh-mode-hook
	      '(lambda()
		 (local-set-key (kbd "C-M-<return>") 'eir-eval-in-shell2)))


    ;;; Scala support
    ;; (require 'ensime) ; if not done elsewhere
    (require 'eval-in-repl-scala)
    (define-key scala-mode-map (kbd "<C-return>") 'eir-eval-in-scala)
  )
#+END_SRC

* Common Lisp

Prerequisites: install SBCL implementation of CLIPS and quicklisp.
Use M-x slime to fire up and connect to an inferior Lisp. SLIME will now automatically be available in Lisp source buffers.
#+BEGIN_SRC emacs-lisp
  (use-package slime
    :ensure t
    :config
    (progn
      (setq inferior-lisp-program "/usr/sbin/sbcl"
            slime-contribs '(slime-fancy)
            lisp-indent-function 'common-lisp-indent-function
            slime-complete-symbol-function 'slime-fuzzy-complete-symbol)
      (slime-setup)))
#+END_SRC

* Scheme
#+BEGIN_SRC emacs-lisp
  ;; Geiser, for Scheme REPL and autodoc;
  ;; use mit-scheme by default
  (use-package geiser
    :ensure t)
  (setq geiser-active-implementations '(mit))
  ;;(setq scheme-program-name "csi -:c")          ; uncomment for Chicken scheme
  (add-hook 'scheme-mode-hook 'geiser-mode)
#+END_SRC

* Scala

#+BEGIN_SRC emacs-lisp
  (use-package ensime
    :ensure t
    :pin melpa-stable)
  (setq
    ensime-sbt-command "/usr/sbin/sbt"
    sbt:program-name "/usr/sbin/sbt")
  (use-package scala-mode
    :interpreter
    ("scala" . scala-mode))
  (use-package sbt-mode
    :commands sbt-start sbt-command
    :config
    ;; WORKAROUND: https://github.com/ensime/emacs-sbt-mode/issues/31
    ;; allows using SPACE when in the minibuffer
    (substitute-key-definition
     'minibuffer-complete-word
     'self-insert-command
     minibuffer-local-completion-map))
#+END_SRC

* Python

** Static analysis for Python

Make sure to =pip install --upgrade flake8= and =pip install virtualenv= first. After installing =jedi=, 
run =M-x jedi:install-server= in Emacs.
#+BEGIN_SRC emacs-lisp
  (use-package jedi
    :ensure t
    :init
    (add-hook 'python-mode-hook 'jedi:setup)
    (add-hook 'python-mode-hook 'jedi:ac-setup)
    (add-to-list 'company-backends 'company-jedi)
    :config
    (use-package company-jedi
      :ensure t
      :init
      (add-hook 'python-mode-hook (lambda () (add-to-list 'company-backends 'company-jedi)))
      (setq company-jedi-python-bin "python")))
#+END_SRC

* Javascript
HTML with web-mode:
#+BEGIN_SRC emacs-lisp
  (use-package web-mode
      :ensure t
      :config
	     (add-to-list 'auto-mode-alist '("\\.html?\\'" . web-mode))
	     (setq web-mode-engines-alist
		   '(("django"    . "\\.html\\'")))
	     (setq web-mode-ac-sources-alist
	     '(("css" . (ac-source-css-property))
	       ("html" . (ac-source-words-in-buffer ac-source-abbrev))))
  (setq web-mode-enable-auto-closing t))
  (setq web-mode-enable-auto-quoting t)

  (defun my-web-mode-hook ()
      (setq web-mode-markup-indent-offset 2)
      (setq web-mode-css-indent-offset 2)
      (setq web-mode-code-indent-offset 2)
      (setq web-mode-indent-style 2))
  (add-hook 'web-mode-hook  'my-web-mode-hook)
#+END_SRC
* Theme

#+BEGIN_SRC emacs-lisp
  ;; spacemacs theme
  (unless (package-installed-p 'spacemacs-theme)
    (package-refresh-contents)
    (package-install 'spacemacs-theme))
  ;; (use-package darkokai-theme
  ;;   :ensure t
  ;;   :config (load-theme 'darkokai t))
#+END_SRC

Set transparency level:
#+BEGIN_SRC emacs-lisp
  ;;(set-frame-parameter (selected-frame) 'alpha '(<active> . <inactive>))
  ;;(set-frame-parameter (selected-frame) 'alpha <both>)
  (set-frame-parameter (selected-frame) 'alpha '(95 50))
  (add-to-list 'default-frame-alist '(alpha 95 50))
#+END_SRC

Transparent background for terminal emulator:
#+BEGIN_SRC emacs-lisp
  (defun on-after-init ()
    (unless (display-graphic-p (selected-frame))
      (set-face-background 'default "unspecified-bg" (selected-frame))))
  (add-hook 'window-setup-hook 'on-after-init)
#+END_SRC

* UI

Start emacs frame full-screen:
#+BEGIN_SRC emacs-lisp
  (setq initial-frame-alist '((top . 0) (left . 0) (width . 177) (height . 53)))
#+END_SRC

* Shell

Make =zsh= default:
#+BEGIN_SRC emacs-lisp
  (defvar my-term-shell "/usr/bin/zsh")
  (defadvice ansi-term (before force-bash)
    (interactive (list my-term-shell)))
  (ad-activate 'ansi-term)
#+END_SRC

* Keybindings

Launch terminal using =<super>-<return>=:
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "<s-return>") 'ansi-term)
  (put 'scroll-left 'disabled nil)
#+END_SRC

Switch window with =C-x o=; resize window with =M-<left|right|up|down>=:
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "M-o") 'other-window)
  (windmove-default-keybindings) ; S-<left|right|up|down> to switch windows

  (global-set-key (kbd "<M-up>") 'shrink-window)
  (global-set-key (kbd "<M-down>") 'enlarge-window)
  (global-set-key (kbd "<M-left>") 'shrink-window-horizontally)
  (global-set-key (kbd "<M-right>") 'enlarge-window-horizontally)
#+END_SRC

Bind Imenu to =M-i=:
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "M-i") 'imenu)
#+END_SRC

Maximize window temporarily with <s-S-return>:
#+BEGIN_SRC emacs-lisp
  (defun toggle-maximize-buffer () "Maximize buffer"
    (interactive)
    (if (= 1 (length (window-list)))
	(jump-to-register '_) 
      (progn
	(window-configuration-to-register '_)
	(delete-other-windows))))
  (global-set-key [(super shift return)] 'toggle-maximize-buffer) 
#+END_SRC

* Aliases

Respond with =y/n= to prompts:
#+BEGIN_SRC emacs-lisp
  (defalias 'yes-or-no-p 'y-or-n-p)
#+END_SRC

ibuffer is more user-friendly for editing buffers:
#+BEGIN_SRC emacs-lisp
  (defalias 'list-buffers 'ibuffer-other-window)
#+END_SRC
* Misc

No splash screen:
#+BEGIN_SRC emacs-lisp
  (setq inhibit-startup-message t)
#+END_SRC

Hide menu mar, scroll line by line, disable bell...
#+BEGIN_SRC emacs-lisp
  ;; in terminal
  (unless (display-graphic-p)
    (menu-bar-mode -1))
  
  ;; in gui
  (when (window-system)
    (scroll-bar-mode -1)
    (tool-bar-mode -1)
    ;;(menu-bar-mode -1)
    (global-hl-line-mode t))  ; highlight line under cursor

  (setq scroll-conservatively 100)

  (setq ring-bell-function 'ignore)
#+END_SRC

Move by visual (not logical) lines; sentences needn't be separated by double spaces:
#+BEGIN_SRC emacs-lisp
  (global-visual-line-mode t)

  (setq sentence-end-double-space nil)
  (xclip-mode 1)
#+END_SRC

No backup~ or =autosave= files:
#+BEGIN_SRC emacs-lisp
  (setq make-backup-files nil
        auto-save-default nil
        create-lockfiles nil)
#+END_SRC


Share system clipboard with emacs:
#+BEGIN_SRC emacs-lisp
  (setq x-select-enable-clipboard t)
#+END_SRC

Line numbers:
#+BEGIN_SRC emacs-lisp
;; ;; show line numbers
;; ;; add space and solid line between line numbers and text
;; (setq linum-format "%4d \u2502 ")
;; (global-linum-mode t)
(global-linum-mode)
#+END_SRC

Turn on highlight matching brackets when cursor is on one:
#+BEGIN_SRC emacs-lisp
  (show-paren-mode 1)
  (setq show-paren-delay 0.5)
#+END_SRC

Show line and column number at cursor by default:
#+BEGIN_SRC emacs-lisp
  (setq line-number-mode t)
  (setq column-number-mode t)
#+END_SRC

Open a vertical split by default:
#+BEGIN_SRC emacs-lisp
  (setq split-height-threshold nil
        split-width-threshold 80) ;; set to e.g. 160 for widescreen monitors
#+END_SRC

Show zero-width chars (https://en.wikipedia.org/wiki/Zero-width_space):
#+BEGIN_SRC emacs-lisp
  (update-glyphless-char-display 'glyphless-char-display-control '((format-control . empty-box) (no-font . hex-code)))
#+END_SRC
